## Numpy array and basics
learn about numpy array and basics

import numpy as np

In [1]:
import numpy as np
arr_1d = np.array([1,2,3,4,5])
print("1D Array:", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D Array:\n", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


##List vs numpy array

In [11]:
py_list = [1,2,3]
print("Python list multiplication ", py_list * 2)

np_array = np.array([1,2,3])
print("Python array multiplication ", np_array * 2)


import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time:", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time:", time.time() - start)





Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time: 0.06788825988769531

 Numpy operation time: 0.005899667739868164


creating array from scratch

In [12]:
zeros = np.zeros((3, 4))
print("zeros array:\n", zeros)

ones = np.ones((2, 3))
print("One array:\n", ones)

full = np.full((2, 2), 7)
print("Full Array:\n", full )

random = np.random.random((2, 3))
print("Random Array:\n", random)

sequence = np.arange(0, 10, 2)
print("sequence array: \n", sequence)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array:
 [[7 7]
 [7 7]]
Random Array:
 [[0.27727238 0.52220459 0.80459575]
 [0.1277515  0.27059365 0.22710978]]
sequence array: 
 [0 2 4 6 8]


##Vector Matrix and Tensor

In [13]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1,2,3], [4,5,6]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2], [3,4]],
                    [[5,6], [7,8]]])
print("Tensor: ", tensor )

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


###Array Properties

In [14]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6],[7,8,9]])

print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("DType", arr.dtype)


Shape (3, 3)
Dimension 2
Size 9
DType int64


###Array Reshaping

In [2]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped Array", reshaped)

flattened = reshaped.flatten()
print("\n Flattened Array", flattened)

raveled = reshaped.ravel()
print("\n Raveled Array", raveled)





Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array [ 0  1  2  3  4  5  6  7  8  9 10 11]
